server:
  port: 8095

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Younisteli/microservice_config
          clone-on-start: true
